# =====================================================================
# CONFIGURACIÓN DE LA BASE DE DATOS EN MEMORIA (H2)
# =====================================================================

# Habilita la consola web de H2 para visualizar las tablas e insertar/consultar datos manualmente
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# URL de conexión persistente en memoria mientras el proceso esté activo
spring.datasource.url=jdbc:h2:mem:ecommercedb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# =====================================================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# =====================================================================

# Hibernate creará las tablas automáticamente basándose en las clases @Entity
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =====================================================================
# INICIALIZACIÓN DE DATOS (data.sql)
# =====================================================================

# Indica a Spring Boot que ejecute el archivo 'data.sql' siempre al arrancar
spring.sql.init.mode=always

# CRUCIAL para Spring Boot 3+:
# Fuerza a que Hibernate cree primero las tablas antes de que se ejecuten los scripts 'data.sql'
spring.jpa.defer-datasource-initialization=true

application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000

# Configuración del servidor de correo (SMTP)
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=0a2c8254cdf315
spring.mail.password=57639c20c11ad5
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
application.security.verification-url=http://localhost:8080/api/v1/auth/confirm

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379