spring.application.name=e-commerce-api

# Configuración para usar base de datos H2 temporal en desarrollo
spring.datasource.url=jdbc:h2:mem:ecommerce_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Permite ver las consultas SQL que genera Hibernate en la consola
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Habilitar la consola web de H2 para visualizar tablas (acceso en http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
